### ISSUE TITLE
Log Messages

### ISSUE THREAD

**Issue by fehza123** [alexandercerutti/passkit-webservice-toolkit#1]
Thanks for all of this - really interesting. 

I am curious - what kind of logEntries can one receive? I tried to find it on the internet (anywhere) and can't seem to understand what is logged. 

My question is if I'd get log notifications for a beacon or location notification is triggered on the lock screen depending on the provided lat/lon. 

Any thoughts there? I am trying to test it myself, but I don't seem to get any logs just yet - just register/deregister.

**Comment by alexandercerutti** [comment]
Hey @fehza123, glad it was helpful to you! Thanks for using it!

Logs are just strings reporting generally issues with your endpoints, crashes or missing implementations, I think.

I was able to see a few while integrating [fastify-passkit-webservice](https://github.com/alexandercerutti/fastify-passkit-webservice).

I don't thing you'll receive logs for beacons and location as they are something that happen on the device. I might be wrong, tho. You can try and check if that happens somehow.

**Comment by fehza123** [comment]
Thank you Alex! Ah I see - yeah I don’t think any service can be notified about the location in the wallet pass. I was mistakenly thinking the logs might, but my testing w location shows they do not.

**Comment by alexandercerutti** [comment]
I think they are just for what concerns the development of the web service 😄

Let me know if we can close this or if you have any further questions 👍

**Comment by fehza123** [comment]
We can close it - thank you very much!

**Comment by alexandercerutti** [comment]
Great! It would be awesome if you could leave a 🌟 on the project 🚀

**Comment by fehza123** [comment]
Of course! Done :)
